// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mafmxoozubqjoydhipbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hZm14b296dWJxam95ZGhpcGJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTA0NzcsImV4cCI6MjA3Mzc4NjQ3N30.t2AegtgKNyztUnDjI7bl85riQeqPqUZuywfrnKWVKX0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});